login:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /inscription
    permanent: true

formDossierEtudiant:
  path: /etudiant/dossier
  controller: App\Controller\DossierEtudiant